sudo: required

language: go

go:
  - 1.16.x

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce
      - make

install:
  - go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.40.1

script:
  - make lint
  - make tests
# TODO: Please uncomment this line to run code challenge
#  - make run
