sudo: required
language: go

go:
  - 1.16.x

addons:
  apt:
    packages:
      - make

install:
  - go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.40.1

script:
  - make lint
  - make tests
# TODO: Please uncomment this line to run code challenge
#  - make run
